export interface BrickSearchResult {
  name: string;
  description: string;
  version: string;
  publisher: string;
  createdAt: string;
}

export interface BrickMetaData extends BrickSearchResult {
  environment: Environment;
  vars: Record<string, BrickVariableProperties>;
  hooks: string[];
}

export interface BrickArtifact extends BrickMetaData {
  readme: string;
  changelog: string;
  license: string;
}

export interface Environment {
  mason: string;
}

export interface BrickVariableProperties {
  type: "string" | "number" | "boolean";
  description?: string;
  default?: string;
  prompt?: string;
}

const baseUrl = process.env.HOSTED_URL;

export async function searchBricks({ query }: { query: string }): Promise<any> {
  const response = await fetch(`${baseUrl}/api/v1/search?q=${query}`);
  const body = await response.json();
  return body.bricks.map((brick: any) => {
    return {
      name: brick.name,
      description: brick.description,
      version: brick.version,
      publisher: brick.publisher,
      createdAt: brick.created_at,
    };
  });
}

export async function getArtifact({
  name,
  version,
}: {
  name: string;
  version: string;
}): Promise<BrickArtifact> {
  const response = await fetch(
    `${baseUrl}/api/v1/bricks/${name}/versions/${version}.bundle`
  );
  const body = await response.json();
  return Object.assign({}, body, {
    createdAt: body.created_at,
    readme: `
# hello
A new brick created with the Mason CLI.

_Generated by [mason][1] 🧱_

## Getting Started 🚀

This is a starting point for a new brick.
A few resources to get you started if this is your first brick template:

- [Official Mason Documentation][2]
- [Code generation with Mason Blog][3]
- [Very Good Livestream: Felix Angelov Demos Mason][4]

[1]: https://github.com/felangel/mason
[2]: https://github.com/felangel/mason/tree/master/packages/mason_cli#readme
[3]: https://verygood.ventures/blog/code-generation-with-mason
[4]: https://youtu.be/G4PTjA6tpTU
`,
    changelog: `# 0.1.0+1

    - TODO: Describe initial release.
    `,
    license: `TODO: Add your license here.
`,
  });
}
